[tool.black]
line-length = 90

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = ["tests/"]

[tool.pytest.ini_options]
log_level = "INFO"

[tool.ruff]
target-version = "py311"
select = ["ALL", "PT"]

ignore = [
    # default
    "ANN101",
    "ANN102",
    "COM812",
    "D107",
    "N812",
    "PTH",

    # project-specific
    "C90",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D415",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PT023",
    "S320",
    "S321",
]

# allow autofix behavior for specified rules
fixable = ["E", "F", "I", "Q"]

# set max line length
line-length = 90

# enumerate all fixed violations
show-fixes = true

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.per-file-ignores]
"tests/**/*" = ["ANN", "ARG001", "S101"]

[tool.ruff.pycodestyle]
max-doc-length = 90

[tool.ruff.pydocstyle]
convention = "google"
