name: Prod Image Promote
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:

  promote:
    name: Prod promote
    uses: mitlibraries/.github/.github/workflows/ecr-multi-arch-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: us-east-1
      GHA_ROLE_STAGE: browsertrix-harvester-gha-stage
      GHA_ROLE_PROD: browsertrix-harvester-gha-prod
      ECR_STAGE: browsertrix-harvester-stage
      ECR_PROD: browsertrix-harvester-prod